version: '3.1'

services:

  front_balancer:
    build: ./front_balancer
    ports:
     - "${WEB_PORT1}:80"
     - "443:443"
    links:
      - frontend
    # TO USE DOCKER ENVIRONMENT
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  frontend:
    build: ./frontend
    volumes:
#    - type: bind
#      source: ./nginx/config
#      target: /usr/local/nginx/conf
#      volume:
#        nocopy: false
#
    - type: volume
      source: asset-volume1
      target: /usr/share/nginx/html
      volume:
        nocopy: false
#
#
#    - ./www/front:/usr/share/nginx/html:ro
#    - asset-volume1:/usr/share/nginx/html
#    - ./nginx/config:/usr/local/nginx/conf:rw
#    ports:
#     - "${WEB_PORT1}:80"
#     - "443:443"
#    links:
#     - backend
#    depends_on:
#      - backend

  backend:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - asset-volume2:/var/www/html/web
      - ./backend/conf/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/conf/apache.conf:/etc/apache2/apache2.conf
      - ./www/back:/var/www/html/web
    ports:
      - "${BACK_PORT}:80"
    links:
      - db
    depends_on:
#      - builder
      - db

  db:
    build: ./db
    restart: always
#    command: --innodb_use_native_aio=0
    volumes:
#     - ./www/db/db.sql:/docker-entrypoint-initdb.d/init.sql
    - ./db/config:/etc/mysql/conf.d
    - ./data/db:/var/lib/mysql
    command:
      #'mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON'
      'mysqld --innodb-flush-method=fsync'
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DBNAME}
    ports: 
      - "${DB_BASE_PORT}:3306"
    depends_on:
      - builder

  db-editor:
    build: ./db-editor
    restart: always
    ports: 
      - "${DB_EDITOR_PORT}:8080"
    depends_on:
      - db
      - builder
    links:
      - db

#  npm-repo:
#    build: ./npm-repo
#    restart: always
#    volumes:
#      - ./npm-repo/storages/npm:/var/storages/npm
 #   ports: 
#    - "4873:4873"
#    links:
#      - builder

  builder:
    build: 
      context: ./
      args:
        - REPO_SHELL=${REPO_SHELL}
        - REPO_SCRIPTS_FOLDER=${REPO_SCRIPTS_FOLDER}
        - FRONT_GIT_REPO=${FRONT_GIT_REPO}
        - BACK_GIT_REPO=${BACK_GIT_REPO}

      dockerfile: ./builder/Dockerfile
    ports:
     - "8200:80"
    volumes:
      - asset-volume1:/repo/front/code/dist/
      - asset-volume2:/repo/back
    env_file: .env





volumes:
  asset-volume1:
  asset-volume2:
